name: Auth CI Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DATABASE_URL: "mysql://root:root@localhost:3307/artisan_marketplace"
  NEXTAUTH_URL: "http://localhost:3000"
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}

jobs:
  auth-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: marketplace_user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: artisan_marketplace
          MYSQL_ROOT_HOST: '%'
        ports: [3307:3306]
        options: >-
          --health-cmd="mysqladmin ping -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Setup Database
        run: |
          npx prisma generate
          npx prisma db push --skip-generate --accept-data-loss
          echo "Database schema synchronized"
      
      - name: Verify Setup
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: |
          # Check tables using direct MySQL client
          mysql -h 127.0.0.1 -P 3307 -uroot -proot artisan_marketplace -e "SHOW TABLES;"
          # Verify Prisma version
          npx prisma --version
      
      - name: Run Auth Tests
        env:
          DATABASE_URL: "mysql://marketplace_user:password@localhost:3307/artisan_marketplace"
        run: npm test -- __tests__/auth.test.js
      
      - name: Build Sign-in Page
        run: npm run build