name: CI Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: marketplace_user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: artisan_marketplace
        ports: [3307:3306]
        options: >-
          --health-cmd="mysqladmin ping -u marketplace_user -ppassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Set up Prisma
        run: npx prisma generate
      
      - name: Run migrations
        env:
          DATABASE_URL: "mysql://marketplace_user:password@localhost:3307/artisan_marketplace"
        run: npx prisma migrate dev --name ci_init --skip-generate
      
      - name: Build application
        run: npm run build
      
      - name: Run tests
        env:
          DATABASE_URL: "mysql://marketplace_user:password@localhost:3307/artisan_marketplace"
          NEXTAUTH_URL: "http://localhost:3000"
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
        run: npm test
      
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        if: success()